-- MySQL Script generated by MySQL Workbench
-- 11/30/16 15:04:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sistemaGestionRRHH` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemaGestionRRHH` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema rrhh
-- -----------------------------------------------------
USE `sistemaGestionRRHH` ;

-- -----------------------------------------------------
-- Table `sistemaGestionRRHH`.`Fichas_Ocupacionales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaGestionRRHH`.`Fichas_Ocupacionales` (
  `idFichas_Ocupacionales` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre Cargo` VARCHAR(45) NULL COMMENT '',
  `Area` VARCHAR(45) NULL COMMENT '',
  `Definicion` VARCHAR(45) NULL COMMENT '',
  `Funciones` VARCHAR(45) NULL COMMENT '',
  `Requisitos` VARCHAR(45) NULL COMMENT '',
  `Salario Base` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idFichas_Ocupacionales`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaGestionRRHH`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaGestionRRHH`.`Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `Apellido` VARCHAR(45) NULL COMMENT '',
  `Direccion` VARCHAR(45) NULL COMMENT '',
  `Cedula` VARCHAR(45) NULL COMMENT '',
  `Telefono` VARCHAR(45) NULL COMMENT '',
  `Estado` VARCHAR(45) NULL COMMENT '',
  `Genero` VARCHAR(1) NOT NULL DEFAULT 0 COMMENT '1 Hombre\n2 Mujer',
  `Fichas_Ocupacionales_idFichas_Ocupacionales` INT NOT NULL COMMENT '',
  `FechaContratacion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idEmpleado`, `Fichas_Ocupacionales_idFichas_Ocupacionales`)  COMMENT '',
  INDEX `fk_Empleado_Fichas_Ocupacionales_idx` (`Fichas_Ocupacionales_idFichas_Ocupacionales` ASC)  COMMENT '',
  CONSTRAINT `fk_Empleado_Fichas_Ocupacionales`
    FOREIGN KEY (`Fichas_Ocupacionales_idFichas_Ocupacionales`)
    REFERENCES `sistemaGestionRRHH`.`Fichas_Ocupacionales` (`idFichas_Ocupacionales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaGestionRRHH`.`Vacaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaGestionRRHH`.`Vacaciones` (
  `idVacaciones` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `FechaInicio` VARCHAR(45) NULL COMMENT '',
  `FechaFin` VARCHAR(45) NULL COMMENT '',
  `Descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idVacaciones`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaGestionRRHH`.`Empleado_has_Vacaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaGestionRRHH`.`Empleado_has_Vacaciones` (
  `Empleado_idEmpleado` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Empleado_Fichas_Ocupacionales_idFichas_Ocupacionales` INT NOT NULL COMMENT '',
  `Vacaciones_idVacaciones` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Empleado_idEmpleado`, `Empleado_Fichas_Ocupacionales_idFichas_Ocupacionales`, `Vacaciones_idVacaciones`)  COMMENT '',
  INDEX `fk_Empleado_has_Vacaciones_Vacaciones1_idx` (`Vacaciones_idVacaciones` ASC)  COMMENT '',
  INDEX `fk_Empleado_has_Vacaciones_Empleado1_idx` (`Empleado_idEmpleado` ASC, `Empleado_Fichas_Ocupacionales_idFichas_Ocupacionales` ASC)  COMMENT '',
  CONSTRAINT `fk_Empleado_has_Vacaciones_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado` , `Empleado_Fichas_Ocupacionales_idFichas_Ocupacionales`)
    REFERENCES `sistemaGestionRRHH`.`Empleado` (`idEmpleado` , `Fichas_Ocupacionales_idFichas_Ocupacionales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_Vacaciones_Vacaciones1`
    FOREIGN KEY (`Vacaciones_idVacaciones`)
    REFERENCES `sistemaGestionRRHH`.`Vacaciones` (`idVacaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaGestionRRHH`.`DiaSemana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaGestionRRHH`.`DiaSemana` (
  `idDiaSemana` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idDiaSemana`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaGestionRRHH`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaGestionRRHH`.`Horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `DiaSemana` VARCHAR(45) NULL COMMENT '',
  `HoraInicio` VARCHAR(45) NULL COMMENT '',
  `HoraFin` VARCHAR(45) NULL COMMENT '',
  `DiaSemana_idDiaSemana` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idHorario`, `DiaSemana_idDiaSemana`)  COMMENT '',
  INDEX `fk_Horario_DiaSemana1_idx` (`DiaSemana_idDiaSemana` ASC)  COMMENT '',
  CONSTRAINT `fk_Horario_DiaSemana1`
    FOREIGN KEY (`DiaSemana_idDiaSemana`)
    REFERENCES `sistemaGestionRRHH`.`DiaSemana` (`idDiaSemana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaGestionRRHH`.`Empleado_has_Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaGestionRRHH`.`Empleado_has_Horario` (
  `Empleado_idEmpleado` INT NOT NULL COMMENT '',
  `Empleado_Fichas_Ocupacionales_idFichas_Ocupacionales` INT NOT NULL COMMENT '',
  `Horario_idHorario` INT NOT NULL COMMENT '',
  `Horario_DiaSemana_idDiaSemana` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Empleado_idEmpleado`, `Empleado_Fichas_Ocupacionales_idFichas_Ocupacionales`, `Horario_idHorario`, `Horario_DiaSemana_idDiaSemana`)  COMMENT '',
  INDEX `fk_Empleado_has_Horario_Horario1_idx` (`Horario_idHorario` ASC, `Horario_DiaSemana_idDiaSemana` ASC)  COMMENT '',
  INDEX `fk_Empleado_has_Horario_Empleado1_idx` (`Empleado_idEmpleado` ASC, `Empleado_Fichas_Ocupacionales_idFichas_Ocupacionales` ASC)  COMMENT '',
  CONSTRAINT `fk_Empleado_has_Horario_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado` , `Empleado_Fichas_Ocupacionales_idFichas_Ocupacionales`)
    REFERENCES `sistemaGestionRRHH`.`Empleado` (`idEmpleado` , `Fichas_Ocupacionales_idFichas_Ocupacionales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_Horario_Horario1`
    FOREIGN KEY (`Horario_idHorario` , `Horario_DiaSemana_idDiaSemana`)
    REFERENCES `sistemaGestionRRHH`.`Horario` (`idHorario` , `DiaSemana_idDiaSemana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaGestionRRHH`.`Pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaGestionRRHH`.`Pagos` (
  `idPagos` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Monto` VARCHAR(45) NULL COMMENT '',
  `FechaPago` VARCHAR(45) NULL COMMENT '',
  `Empleado_idEmpleado` INT NOT NULL COMMENT '',
  `Empleado_Fichas_Ocupacionales_idFichas_Ocupacionales` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idPagos`, `Empleado_idEmpleado`, `Empleado_Fichas_Ocupacionales_idFichas_Ocupacionales`)  COMMENT '',
  INDEX `fk_Pagos_Empleado1_idx` (`Empleado_idEmpleado` ASC, `Empleado_Fichas_Ocupacionales_idFichas_Ocupacionales` ASC)  COMMENT '',
  CONSTRAINT `fk_Pagos_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado` , `Empleado_Fichas_Ocupacionales_idFichas_Ocupacionales`)
    REFERENCES `sistemaGestionRRHH`.`Empleado` (`idEmpleado` , `Fichas_Ocupacionales_idFichas_Ocupacionales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaGestionRRHH`.`EntradaSalida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaGestionRRHH`.`EntradaSalida` (
  `idEntradaSalida` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Fecha` DATE NULL COMMENT '',
  `HoraEntrada` TIME NULL COMMENT '',
  `HoraSalida` TIME NULL COMMENT '',
  `Empleado_idEmpleado` INT NOT NULL COMMENT '',
  `Empleado_Fichas_Ocupacionales_idFichas_Ocupacionales` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idEntradaSalida`, `Empleado_idEmpleado`, `Empleado_Fichas_Ocupacionales_idFichas_Ocupacionales`)  COMMENT '',
  INDEX `fk_EntradaSalida_Empleado1_idx` (`Empleado_idEmpleado` ASC, `Empleado_Fichas_Ocupacionales_idFichas_Ocupacionales` ASC)  COMMENT '',
  CONSTRAINT `fk_EntradaSalida_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado` , `Empleado_Fichas_Ocupacionales_idFichas_Ocupacionales`)
    REFERENCES `sistemaGestionRRHH`.`Empleado` (`idEmpleado` , `Fichas_Ocupacionales_idFichas_Ocupacionales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
